/* The Journey of One Box · amyra-ind-usa-export · MIT License · https://games.edock.io/amyra-ind-usa-export */
/* ============ HINGLISH ============ */
/* Every line a player reads, in Hinglish: Hindi written in English letters, the way people text.
   The key is the exact English line. A line with no entry shows in English, so a missing one never
   breaks the game; `node tools/hinglish-check.js` lists what is missing and what is no longer used.
   Words in {braces} are filled in by the game: keep them, in any order.
   Official names stay in English on purpose (IEC, LUT, GST, AD Code, EIN, W-8BEN, FDA, CPC, FBA,
   FIRA, e-BRC, Brand Registry), because those are the words players will meet on real forms.
   Instructions use the polite "-ein" form (chunein, karein). The share message is written the way a
   friend would send it (khelo). */
const HINGLISH={
 /* products */
 'Copper bottle':'Copper ki bottle',
 'Light, tough, India-famous':'Halki, mazboot, India ki pehchaan',
 'Can I keep lemon water in it?':'Kya isme nimbu paani rakh sakte hain?',
 'No, plain water only':'Nahi, sirf saada paani',
 'Yes, any drink':'Haan, koi bhi drink',
 'Copper reacts with sour drinks. A false yes brings sick customers and returns.':'Copper khatti cheezon se react karta hai. Galat "haan" se customer beemar padenge aur returns aayenge.',
 'Spice blend':'Masala mix',
 'Cheap to make, food rules apply':'Banana sasta, par food ke rules lagte hain',
 'Does it contain nuts? My son is allergic.':'Kya isme nuts hain? Mere bete ko allergy hai.',
 'Answer from the allergen label':'Allergen label dekhkar jawab dein',
 'Probably not':'Shayad nahi',
 'A guess about allergies can put a child in hospital. Answer only from the label.':'Allergy par andaaza bachche ko hospital pahuncha sakta hai. Sirf label dekhkar jawab dein.',
 'Wooden toy':'Lakdi ka khilona',
 'Loved abroad, safety tests apply':'Videsh mein pasand, safety test zaroori',
 'Is it safe for my 1-year-old?':'Kya ye mere 1 saal ke bachche ke liye safe hai?',
 'No, it is for age 3 and up':'Nahi, ye 3 saal aur usse bade bachchon ke liye hai',
 'Yes, any age':'Haan, har umar ke liye',
 'Small parts can choke a baby. The age on the label is there for a reason.':'Chhote parts baby ke gale mein atak sakte hain. Label par umar yunhi nahi likhi.',
 'Cotton throw':'Cotton ki chaadar',
 'Good price, bulky to ship':'Achha daam, par bhejne mein bhaari',
 'Can I wash it in hot water?':'Kya ise garam paani mein dho sakte hain?',
 'No, wash cold, as the label says':'Nahi, thande paani mein, jaisa label par likha hai',
 'Yes, hot is fine':'Haan, garam chalega',
 'Hot water shrinks cotton. Every shrunk throw comes back as a return.':'Garam paani se cotton sikud jaata hai. Har sikudi chaadar return ban kar wapas aati hai.',
 'Pain relief balm':'Dard ka balm',
 'India-famous, but a medicine in the US':'India mein mashhoor, par US mein ye dawai hai',
 'Can I use it on my 1-year-old?':'Kya ise apne 1 saal ke bachche par laga sakte hain?',
 'No, ask a doctor under age 2':'Nahi, 2 saal se chhote ke liye doctor se poochhein',
 'Yes, it is all natural':'Haan, ye poori tarah natural hai',
 'Camphor can harm small children. The label says: under 2 years, ask a doctor.':'Kapoor chhote bachchon ko nuksaan pahuncha sakta hai. Label kehta hai: 2 saal se kam, doctor se poochhein.',
 '{name}. Factory cost about {cost} a piece, sells for {price} on Amazon USA.':'{name}. Banane mein lagbhag {cost} per piece, Amazon USA par {price} mein bikti hai.',

 /* stamps: names stay official, meanings in Hinglish */
 'Golden sample':'Golden sample',
 'The one approved piece. Every unit must match it.':'Wo ek pass kiya hua piece. Har unit bilkul waisa hona chahiye.',
 'Design paper':'Design ka kaagaz',
 'Written proof the design and moulds are yours.':'Likha hua saboot ki design aur moulds aapke hain.',
 'Trademark':'Trademark',
 'Your brand name booked in the USA. Pending is enough for Amazon.':'USA mein aapka brand naam book. Amazon ke liye pending bhi kaafi hai.',
 'IEC':'IEC',
 'India’s 10-digit exporter ID. Confirm it every year.':'India ka 10 digit exporter ID. Har saal confirm karein.',
 'GST number':'GST number',
 'Business tax number. Needed to export as a business.':'Business ka tax number. Business ke roop mein export ke liye zaroori.',
 'LUT':'LUT',
 'Promise letter: export now, skip 18% tax upfront.':'Vaade ki chitthi: abhi export karein, 18% tax pehle na bharein.',
 'AD Code':'AD Code',
 'Your bank’s code with customs, so foreign money can land.':'Customs ke paas aapke bank ka code, taaki videshi paisa aa sake.',
 'Seller account':'Seller account',
 'Your shop on Amazon USA.':'Amazon USA par aapki dukaan.',
 'EIN':'EIN',
 'Free US tax number for your business.':'Aapke business ka free US tax number.',
 'W-8BEN':'W-8BEN',
 'Says you live outside the US. No 30% cut on payouts.':'Batata hai ki aap US se bahar rehte hain. Payout se 30% nahi katega.',
 'First batch':'Pehla batch',
 'The full run, brand printed on every unit.':'Poora production, har unit par brand chhapa hua.',
 'Brand Registry':'Brand Registry',
 'Amazon agrees the brand is yours. Unlocks A+, Vine, protection.':'Amazon maanta hai ki brand aapka hai. A+, Vine aur protection khul jaate hain.',
 'GS1 barcode':'GS1 barcode',
 'Genuine barcode numbers for your listing.':'Aapki listing ke liye asli barcode number.',
 'FDA registered':'FDA registered',
 'Factory on the US food authority’s list, with a US agent.':'Factory US food authority ki list mein, ek US agent ke saath.',
 'CPC':'CPC',
 'Toy lab-tested to the US standard, certificate written.':'Khilona US standard par lab mein test hua, certificate bana.',
 'FDA drug listing':'FDA drug listing',
 'Balm listed with FDA as an over-the-counter medicine, with its own NDC number.':'Balm FDA mein bina parchi wali dawai ke roop mein listed, apne NDC number ke saath.',
 'US label':'US label',
 'Fibre, care and origin, written the American way.':'Fibre, dhulai aur origin, American tareeke se likha hua.',
 'Made in India':'Made in India',
 'Country of origin marked for good. Every import needs it.':'Kis desh mein bana, hamesha ke liye likha. Har import par zaroori.',
 'Listing live':'Listing live',
 'Photos, words and A+ ready.':'Photos, shabd aur A+ taiyaar.',
 'Shipping bill':'Shipping bill',
 'Customs proof the goods left India. Open until paid.':'Customs ka saboot ki maal India se nikla. Paisa aane tak khula rehta hai.',
 'Importer of Record':'Importer of Record',
 'The name that answers to US customs. Never Amazon.':'Wo naam jo US customs ko jawab deta hai. Kabhi Amazon nahi.',
 'In FBA':'In FBA',
 'Stock inside Amazon’s warehouse.':'Amazon ke warehouse mein stock.',
 'Launched':'Launched',
 'Ads on, honest reviews coming.':'Ads chalu, sachche reviews aa rahe hain.',
 'FIRA':'FIRA',
 'Bank receipt: the dollars arrived.':'Bank ki raseed: dollar aa gaye.',
 'e-BRC':'e-BRC',
 'Official closing certificate. Promise kept.':'Sarkari closing certificate. Vaada poora.',

 /* ranks */
 'Export champion':'Export ke ustaad',
 'Export pro':'Export pro',
 'Smart exporter':'Samajhdaar exporter',
 'Quick learner':'Tez seekhne wale',
 'First-timer':'Naye khiladi',

 /* 1 Bazaar */
 'Bazaar':'Bazaar',
 'Pick your product':'Apna product chunein',
 'What will your box carry?':'Aapke box mein kya jaayega?',
 'Pick something people abroad already buy and India makes well. Small, light, hard to break, not too cheap.':'Aisi cheez chunein jo videsh mein log pehle se khareedte hain aur India achhi banata hai. Chhoti, halki, jaldi na toote, aur bahut sasti na ho.',
 /* 2 Workshop */
 'Workshop':'Workshop',
 'Find your maker':'Apna maker dhoondein',
 'Three workshops. Samples first.':'Teen workshop. Pehle samples.',
 'India makes things in clusters: brass in Moradabad, toys in Channapatna, textiles in Panipat. Get samples from three makers before choosing.':'India mein cheezein clusters mein banti hain: Moradabad mein peetal, Channapatna mein khilone, Panipat mein kapda. Chunne se pehle teen makers se samples mangaiye.',
 'Which maker gets the order?':'Order kis maker ko milega?',
 'Maker A':'Maker A',
 'Great quality, pricey, slow to reply. It works, but budget more per unit.':'Quality badhiya, daam zyada, jawab der se. Chalega, par har unit ka budget zyada rakhein.',
 'Maker B':'Maker B',
 'Good quality, fair price, replies fast. The one you can build a brand on.':'Achhi quality, sahi daam, jaldi jawab. Iske saath brand ban sakta hai.',
 'Maker C':'Maker C',
 'Cheapest, no samples. The trial batch came back cracked. Try again.':'Sabse sasta, koi sample nahi. Trial batch toota hua aaya. Phir se chunein.',
 'Who owns the design?':'Design kiska hai?',
 'Sign a paper':'Kaagaz par sign',
 'In writing: design, moulds and artwork are yours.':'Likhit mein: design, moulds aur artwork aapke.',
 'Handshake':'Haath milana',
 'Without paper, the maker can legally sell your design to the next buyer. Sign it.':'Kaagaz ke bina maker aapka design kanooni taur par agle buyer ko bech sakta hai. Sign karwaiye.',
 /* 3 Cyber Café */
 'Cyber Café':'Cyber Café',
 'Claim your brand name in the USA':'USA mein apna brand naam pakka karein',
 'Name it, check it is free, file it.':'Naam rakhein, check karein ki khaali hai, file karein.',
 'A trademark is the government writing down that a name is yours, country by country. An Indian one means nothing in the USA. Amazon accepts a filed, still-pending application.':'Trademark matlab sarkar likh deti hai ki naam aapka hai, har desh mein alag. India ka trademark USA mein kaam nahi aata. Amazon file ki hui, pending application bhi maan leta hai.',
 'Searched the US trademark database: {brand} is free in your class.':'US trademark database mein dekha: aapki class mein {brand} khaali hai.',
 'File it in the US trademark office?':'US trademark office mein file karein?',
 'File now':'Abhi file karein',
 'Filed through a US attorney. You get a serial number today. Registration takes a year, but pending is enough.':'US attorney ke zariye file hua. Serial number aaj hi mil gaya. Registration mein saal lagta hai, par pending kaafi hai.',
 'Later, save money':'Baad mein, paise bachayein',
 'Saved for now. Remember this moment.':'Abhi ke liye bach gaye. Ye pal yaad rakhiye.',
 /* 4 DGFT */
 'DGFT':'DGFT',
 'Get your exporter ID':'Apna exporter ID lein',
 'Ten digits. Yours for life.':'Das digit. Zindagi bhar aapka.',
 'The Importer Exporter Code is India’s permission slip. Online, small fee, linked to your PAN. Re-confirm it every year or it switches off.':'Importer Exporter Code India ki permission slip hai. Online, chhoti si fees, aapke PAN se juda. Har saal dobara confirm karein, warna band ho jaata hai.',
 'Apply online and stamp it.':'Online apply karein aur stamp lagwayein.',
 'Stamp my IEC':'Mera IEC stamp karein',
 'Done. Every shipping document from now on carries this number.':'Ho gaya. Ab se har shipping document par yahi number hoga.',
 /* 5 GST Office */
 'GST Office':'GST Office',
 'Skip the upfront tax':'Pehle tax bharne se bachein',
 'Register, then sign a promise letter.':'Register karein, phir vaade ki chitthi sign karein.',
 'Exports are tax-free, but the default makes you pay 18% first and claim it back months later. The Letter of Undertaking is a promise to bring the money home, so you skip paying. Renew every April.':'Export par tax nahi lagta, par normally pehle 18% bharna padta hai aur mahino baad wapas milta hai. Letter of Undertaking vaada hai ki paisa ghar laayenge, isliye bharna nahi padta. Har April renew karein.',
 'Register your business for GST.':'Apne business ka GST registration karein.',
 'Register (via CA)':'Register (CA ke zariye)',
 'You now have a GST number.':'Ab aapke paas GST number hai.',
 'How will you handle export tax?':'Export tax ka kya karenge?',
 'Sign the promise letter':'Vaade ki chitthi sign karein',
 'LUT signed. No tax paid upfront. You promised to bring the money home within 9 months.':'LUT sign ho gaya. Pehle koi tax nahi. Aapne vaada kiya ki 9 mahine mein paisa ghar laayenge.',
 'Pay 18% now, claim later':'Abhi 18% bharein, baad mein claim',
 'Legal, but that cash is now stuck in a refund queue for months.':'Kanooni hai, par wo paisa ab mahino tak refund ki line mein atka rahega.',
 /* 6 Bank */
 'Bank':'Bank',
 'Give customs your bank code':'Customs ko apna bank code dein',
 'So foreign money knows where to land.':'Taaki videshi paise ko pata ho kahan aana hai.',
 'The AD Code is a 14-digit code from the branch holding your business account. You register it on the customs portal once per port. Without it the port cannot create your shipping bill.':'AD Code 14 digit ka code hai, us branch se jahan aapka business account hai. Customs portal par har port ke liye ek baar register hota hai. Iske bina port aapka shipping bill nahi bana sakta.',
 'Which account?':'Kaunsa account?',
 'Business current a/c':'Business current a/c',
 'Right one. Separate business money means clean bank proofs later.':'Sahi. Business ka paisa alag rahega to baad mein bank ke saboot saaf rahenge.',
 'Personal savings':'Personal savings',
 'Bank says no. Export money needs a business account.':'Bank mana karta hai. Export ke paise ke liye business account chahiye.',
 'Register the code with customs.':'Customs ke saath code register karein.',
 'Register AD Code':'AD Code register karein',
 'Registered on the customs portal. The port can now issue your papers.':'Customs portal par register ho gaya. Ab port aapke kaagaz bana sakta hai.',
 /* 7 Seller Central */
 'Seller Central':'Seller Central',
 'Open your Amazon USA shop':'Apni Amazon USA dukaan kholein',
 'ID check, then the US tax office.':'Pehle ID check, phir US tax office.',
 'Indian residents sign up through Amazon Global Selling with PAN, ID, bank account and IEC. For the USA add a free tax number (EIN) and a form that says you live outside the US, so Amazon does not keep 30% of your payouts.':'India mein rehne wale Amazon Global Selling se sign up karte hain: PAN, ID, bank account aur IEC ke saath. USA ke liye ek free tax number (EIN) aur ek form bhi chahiye jo batata hai ki aap US se bahar rehte hain, taaki Amazon payout ka 30% na rakhe.',
 'Amazon checks your documents.':'Amazon aapke documents check karta hai.',
 'Names match everywhere':'Har jagah naam same',
 'Verified on video call. Seller plan paid for 3 months.':'Video call par verify ho gaya. 3 mahine ka seller plan bhar diya.',
 'Ravi K. on one, Ravi Kumar on another':'Ek par Ravi K., doosre par Ravi Kumar',
 'Rejected. Every document must match, letter for letter.':'Reject. Har document mein naam akshar-akshar same hona chahiye.',
 'Tax interview: do you live outside the USA?':'Tax interview: kya aap USA se bahar rehte hain?',
 'Yes, sign W-8BEN':'Haan, W-8BEN sign karein',
 'No US tax will be held back from your payouts.':'Aapke payout se koi US tax nahi katega.',
 'Skip the form':'Form chhod dein',
 'Amazon would keep up to 30% of every payout. Sign it.':'Amazon har payout ka 30% tak rakh lega. Sign karein.',
 'Get a free US tax number.':'Free US tax number lein.',
 'Fax form to the IRS':'IRS ko form fax karein',
 'EIN arrived by fax. Free, and no US company needed.':'EIN fax se aa gaya. Free, aur US company ki zaroorat nahi.',
 /* 8 Factory */
 'Factory':'Factory',
 'Make 300 units, brand on them':'300 units banayein, brand ke saath',
 'The name must be part of the product.':'Naam product ka hissa hona chahiye.',
 'Amazon’s brand programme wants real photos of the brand printed, engraved or woven on, not a sticker and not a design file. So the first run comes before you can finish registering the brand.':'Amazon ke brand programme ko asli photos chahiye jahan brand chhapa, khuda ya buna ho. Sticker ya design file nahi chalegi. Isliye pehla production brand registration poora hone se pehle hota hai.',
 'How does your brand go on?':'Brand product par kaise lagega?',
 'Printed and engraved':'Chhapa aur khuda hua',
 'Permanent. Exactly what Amazon wants to see.':'Pakka. Amazon bilkul yahi dekhna chahta hai.',
 'Paper sticker':'Kaagaz ka sticker',
 'Cheaper today. Stickers peel, and Amazon knows it.':'Aaj sasta. Sticker utar jaate hain, aur Amazon ye jaanta hai.',
 'No brand, plain':'Bina brand, saada',
 'Then it is nobody’s product. Anyone can copy the listing.':'Phir ye kisi ka product nahi. Koi bhi listing copy kar sakta hai.',
 'Check the batch before it leaves?':'Bhejne se pehle batch check karein?',
 'Hire an inspector':'Inspector rakhein',
 'Inspector found 6 bad units. Fixed before shipping.':'Inspector ne 6 kharab units pakde. Bhejne se pehle theek ho gaye.',
 'Trust the maker':'Maker par bharosa',
 'Saved a little. You will find out in the reviews.':'Thoda bacha liya. Reviews mein pata chal jaayega.',
 'Photograph product and box with the brand.':'Brand ke saath product aur box ki photo lein.',
 'Take the photos':'Photos lein',
 'Plain table, good light, brand visible. Saved.':'Saada table, achhi roshni, brand dikh raha hai. Save ho gaya.',
 /* 9 Brand Registry */
 'Prove the brand is yours':'Saabit karein ki brand aapka hai',
 'The guard checks two things.':'Guard do cheezein check karta hai.',
 'Brand Registry is free and unlocks rich pages, better ads and copycat takedowns. It needs a trademark that is filed or registered, and photos of the brand permanently on the product.':'Brand Registry free hai. Isse achhe pages, behtar ads aur nakalchi hatane ki taaqat milti hai. Iske liye file ya register hua trademark chahiye, aur product par pakka laga brand dikhane wali photos.',
 'Guard: no trademark, no entry.':'Guard: trademark nahi, to entry nahi.',
 'File it now':'Abhi file karein',
 'Filed. Three weeks lost waiting for the serial number. Next time, file first.':'File ho gaya. Serial number ke intezaar mein teen hafte gaye. Agli baar pehle file karein.',
 'Guard: a sticker? Rejected.':'Guard: sticker? Reject.',
 'Reprint the boxes':'Boxes dobara chhapwayein',
 'Boxes reprinted with the brand on. Two weeks and ₹9,000 gone.':'Brand ke saath boxes dobara chhape. Do hafte aur ₹9,000 gaye.',
 'Upload the real photos and the serial number.':'Asli photos aur serial number upload karein.',
 'Submit':'Submit karein',
 'Approved. Your listings are now locked to you.':'Approve ho gaya. Ab aapki listings sirf aapki hain.',
 'Barcodes for the listing.':'Listing ke liye barcodes.',
 'GS1 official':'GS1 official',
 'Genuine numbers, accepted first time.':'Asli number, pehli baar mein accept.',
 'Cheap ones on Telegram':'Telegram wale saste',
 'Rejected. Resold barcodes belong to someone else.':'Reject. Dobara beche gaye barcode kisi aur ke hote hain.',
 /* 10 Rules Lab */
 'Rules Lab':'Rules Lab',
 'Pass the US product rules':'US ke product rules paas karein',
 'India’s rules do not travel with the goods.':'India ke rules maal ke saath nahi jaate.',
 'Every country decides what is safe and honestly labelled. Food, medicines, skin products and children’s items have real checklists. Everything needs a permanent Made in India mark.':'Har desh khud tay karta hai ki kya safe hai aur label sahi hai. Khaane, dawaiyon, skin products aur bachchon ki cheezon ki poori checklist hoti hai. Har cheez par pakka Made in India mark chahiye.',
 'Food going to the USA.':'Khaane ka saamaan USA ja raha hai.',
 'Register factory with FDA':'Factory FDA mein register karein',
 'Factory registered, US agent named. Each shipment gets announced in advance.':'Factory register, US agent tay. Har shipment ki pehle se soochna jaati hai.',
 'Pick the label the USA accepts.':'Wo label chunein jo USA maanta hai.',
 'Nutrition panel, allergens':'Nutrition panel, allergens',
 'Correct format. Ingredients in order, allergens named.':'Sahi format. Ingredients kram se, allergens ke naam ke saath.',
 'Plain Hindi label':'Sirf Hindi label',
 'Customs can hold or destroy this. Redo it.':'Customs ise rok ya nasht kar sakta hai. Dobara banayein.',
 'A toy needs a lab test.':'Khilone ka lab test zaroori hai.',
 'Send to approved lab':'Approved lab bhejein',
 'Passed the US toy standard. Certificate written. Amazon opens the toy category.':'US toy standard paas. Certificate bana. Amazon ne toy category khol di.',
 'Tracking label, age mark':'Tracking label, umar ka mark',
 'Permanent tracking label on every toy.':'Har khilone par pakka tracking label.',
 'No label':'Koi label nahi',
 'Every children’s item needs one. Redo it.':'Bachchon ki har cheez par chahiye. Dobara karein.',
 'A pain balm is a medicine in the USA. Its factory must be on FDA’s drug list.':'USA mein dard ka balm dawai hai. Uski factory FDA ki drug list mein honi chahiye.',
 'Use a maker already listed':'Pehle se listed maker lein',
 'Their factory is registered with FDA and pays the yearly fee. Your brand gets its own NDC number under it.':'Unki factory FDA mein registered hai aur saal ki fees bharti hai. Aapke brand ko uske tahat apna NDC number milta hai.',
 'Register a new factory':'Nayi factory register karein',
 'A medicine factory pays FDA about {fee} a year before it sells a single tin. Too much for 300 tins. Work with a maker already on the list.':'Dawai ki factory ek bhi dibba bechne se pehle FDA ko har saal lagbhag {fee} deti hai. 300 dibbon ke liye ye bahut zyada hai. Pehle se listed maker ke saath kaam karein.',
 'Drug Facts panel':'Drug Facts panel',
 'Active ingredients with amounts, uses, warnings and directions, in the US format. Every OTC medicine carries one.':'Active ingredients unki matra ke saath, upyog, chetavani aur lagane ka tareeka, US format mein. Har OTC dawai par hota hai.',
 'Ayurvedic, cures 40 pains':'Ayurvedic, 40 dard mitaye',
 'Cure claims and no warnings make it an unapproved drug in the US. Customs can refuse it.':'Ilaaj ke daave aur chetavani na hone se ye US mein bina approval ki dawai ban jaati hai. Customs ise rok sakta hai.',
 'Fibre, care, origin':'Fibre, dhulai, origin',
 '100% cotton, wash cold, Made in India. Sewn in.':'100% cotton, thande paani mein dhoyein, Made in India. Sil diya.',
 'Brand name only':'Sirf brand naam',
 'US law wants fibre content and care instructions. Redo it.':'US kanoon ko fibre aur dhulai ki jaankari chahiye. Dobara karein.',
 'Any claims on the box?':'Box par koi daava?',
 'Keeps water cool':'Paani thanda rakhe',
 'A plain, true claim. Fine.':'Seedha, sachcha daava. Theek hai.',
 'Cures 40 diseases':'40 bimaariyan theek kare',
 'A health claim needs approval. Amazon will pull the listing.':'Health claim ke liye approval chahiye. Amazon listing hata dega.',
 'Country of origin mark.':'Country of origin mark.',
 'Made in India, permanent':'Made in India, pakka',
 'Marked. US customs checks every import for this.':'Mark ho gaya. US customs har import mein ye check karta hai.',
 'Skip it':'Chhod dein',
 'Not optional. Shipments without it get held.':'Ye zaroori hai. Iske bina shipment ruk jaata hai.',
 /* 11 Photo Studio */
 'Photo Studio':'Photo Studio',
 'Build the listing':'Listing banayein',
 'Photos sell. Words get found.':'Photos bechti hain. Shabd dhoondhne mein madad karte hain.',
 'Shoppers decide from the first photo: pure white background, product filling the frame. Lower on the page, brand owners add picture-rich A+ content. Use the words Americans type, not the Hindi ones.':'Shopper pehli photo se faisla karte hain: bilkul safed background, product poore frame mein. Page par neeche brand owner photos wala A+ content lagate hain. Wahi shabd use karein jo American type karte hain, Hindi wale nahi.',
 'Pick the main photo.':'Main photo chunein.',
 'White background, big':'Safed background, bada',
 'Amazon’s rule and the shopper’s favourite.':'Amazon ka rule aur shopper ki pasand.',
 'On the kitchen table':'Kitchen table par',
 'Rejected as a main image. Too busy, product too small.':'Main image ke roop mein reject. Bahut bheed, product bahut chhota.',
 'A drawing of it':'Uski drawing',
 'Mock-ups are not allowed. Real photos only.':'Mock-up allowed nahi. Sirf asli photos.',
 'Americans search for…':'American search karte hain…',
 'That is what they type. Title, bullets, hidden keywords.':'Yahi wo type karte hain. Title, bullets aur hidden keywords mein daalein.',
 'Nobody in Ohio searches that. Try again.':'Ohio mein koi ye search nahi karta. Phir koshish karein.',
 'Add the picture-rich section.':'Photos wala section jodein.',
 'Build A+ content':'A+ content banayein',
 'Banners, a comparison chart, the artisan’s story. Listing is live.':'Banners, comparison chart, kaarigar ki kahani. Listing live hai.',
 /* 12 Port */
 'Port':'Port',
 'Ship the boxes':'Boxes bhejein',
 'And decide who answers to US customs.':'Aur tay karein ki US customs ko jawab kaun dega.',
 'A freight forwarder is a travel agent for cargo. Sea is cheap and slow, air is fast and pricey. On the US side someone must sign the customs entry and pay duty. Amazon refuses that role.':'Freight forwarder maal ka travel agent hai. Samundar sasta aur dheema, hawai jahaz tez aur mehenga. US mein kisi ko customs entry sign karke duty bharni hoti hai. Amazon ye kaam nahi karta.',
 'How do 300 units cross?':'300 units kaise jaayenge?',
 'Ship':'Jahaz',
 'Cheap. About 7 weeks door to door.':'Sasta. Darwaze se darwaze tak lagbhag 7 hafte.',
 'Plane':'Hawai jahaz',
 'There in a week, at nearly three times the price. Fine for a first small batch.':'Ek hafte mein pahunch, par lagbhag teen guna daam. Pehle chhote batch ke liye theek.',
 '300 small parcels':'300 chhote parcel',
 'The duty-free parcel shortcut ended in 2025. Each one gets stopped. No.':'Bina duty wale parcel ka shortcut 2025 mein band ho gaya. Har parcel rukega. Nahi.',
 'Who signs at US customs?':'US customs par sign kaun karega?',
 'Amazon':'Amazon',
 'Amazon never acts as importer. The boxes would sit at the port.':'Amazon kabhi importer nahi banta. Boxes port par pade rahenge.',
 'Me, with a customs bond':'Main, customs bond ke saath',
 'You are the importer, from India. Bond bought with your EIN.':'India se aap hi importer hain. Aapke EIN se bond khareed liya.',
 'A customs broker':'Customs broker',
 'The broker imports in your name and files everything.':'Broker aapke naam se import karta hai aur sab file karta hai.',
 'Customs issues the export paper.':'Customs export ka kaagaz deta hai.',
 'Get the shipping bill':'Shipping bill lein',
 'Goods have officially left India. This paper stays open until the money comes home.':'Maal officially India se nikal gaya. Paisa ghar aane tak ye kaagaz khula rehta hai.',
 /* 13 US Customs */
 'US Customs':'US Customs',
 'Welcome to America':'America mein swagat hai',
 'Answer the officer, pay duty, roll on.':'Officer ko jawab dein, duty bharein, aage badhein.',
 'Duty depends on your product code and it changed several times in 2025 and 2026. Check the current rate before you set a price.':'Duty aapke product code par depend karti hai, aur 2025 aur 2026 mein kai baar badli. Daam tay karne se pehle aaj ka rate check karein.',
 'Officer’s question {i} of {n}: which stamp means this?':'Officer ka sawaal {i}/{n}: kis stamp ka ye matlab hai?',
 'Correct. The officer nods.':'Sahi. Officer ne sir hilaya.',
 'No. {name} means: {meaning}':'Nahi. {name} ka matlab: {meaning}',
 'Pay the import duty.':'Import duty bharein.',
 'Pay duty':'Duty bharein',
 'Cleared. The truck rolls to the warehouse.':'Clear. Truck warehouse ki taraf chal pada.',
 /* 14 FBA Warehouse */
 'FBA Warehouse':'FBA Warehouse',
 'Stock in, launch on':'Stock andar, launch shuru',
 'Amazon stores, packs and ships for you.':'Amazon aapke liye rakhta, pack karta aur bhejta hai.',
 'A new listing has no reviews, so search barely shows it. Ads buy the first visits. Amazon Vine gives free units to trusted reviewers for honest reviews. Fake reviews end accounts.':'Nayi listing par reviews nahi hote, isliye search mein mushkil se dikhti hai. Pehle visitors ads se aate hain. Amazon Vine bharosemand reviewers ko free units deta hai, sachche reviews ke liye. Fake reviews se account band ho jaata hai.',
 'Boxes arrive with Amazon’s labels.':'Boxes Amazon ke labels ke saath pahunche.',
 'Check them in':'Check in karein',
 'Stock live. Amazon now packs every order and handles returns.':'Stock live. Ab Amazon har order pack karta hai aur returns sambhalta hai.',
 'First month of ads?':'Pehle mahine ke ads?',
 'Small budget':'Chhota budget',
 'Slow start. Fewer visits, fewer sales.':'Dheemi shuruaat. Kam visitors, kam sales.',
 'Steady budget':'Theek-thaak budget',
 'Enough clicks to learn which words sell.':'Itne clicks ki pata chale kaunse shabd bikte hain.',
 'Everything':'Sab kuch',
 'Money burns fast on a page with no reviews yet.':'Bina reviews wale page par paisa tezi se jalta hai.',
 'How do you get the first reviews?':'Pehle reviews kaise laayenge?',
 'Amazon Vine':'Amazon Vine',
 'Honest reviews from vetted reviewers. Sales begin.':'Jaanche-parkhe reviewers se sachche reviews. Sales shuru.',
 'Request a Review button':'Request a Review button',
 'Free and allowed. Slower, but it adds up.':'Free aur allowed. Dheema, par dheere-dheere badhta hai.',
 'Buy 50 five-star reviews':'50 five-star reviews khareedein',
 'Account suspended. Money frozen. Appeal cost ₹20,000 and a month. Never again.':'Account suspend. Paisa freeze. Appeal mein ₹20,000 aur ek mahina gaya. Dobara kabhi nahi.',
 /* 15 Customer */
 'Customer':'Customer',
 'Delivered':'Deliver ho gaya',
 'Someone in Ohio just paid for your box.':'Ohio mein kisi ne abhi aapke box ke paise diye.',
 'The customer pays Amazon in dollars. Amazon keeps its fees and pays you every two weeks.':'Customer Amazon ko dollar mein paise deta hai. Amazon apni fees rakhkar har do hafte aapko paise deta hai.',
 'Ring the bell.':'Ghanti bajayein.',
 'Deliver':'Deliver karein',
 'Five stars. Now the money has to come home.':'Five stars. Ab paisa ghar aana hai.',
 /* 16 Your Bank */
 'Your Bank':'Aapka Bank',
 'The money lands':'Paisa aa gaya',
 'Dollars in, rupees out, one receipt.':'Dollar aaye, rupaye bane, ek raseed.',
 'Amazon pays roughly every 14 days. Dollars become rupees on the way. Each time, ask the bank for the receipt proving foreign money arrived.':'Amazon lagbhag har 14 din mein paise deta hai. Raaste mein dollar rupaye ban jaate hain. Har baar bank se wo raseed maangein jo saabit kare ki videshi paisa aaya.',
 'Payout arrived. Ask for the receipt.':'Payout aa gaya. Raseed maangein.',
 'Collect FIRA':'FIRA lein',
 'Receipt in your name, amount in dollars. Keep every one.':'Raseed aapke naam, rakam dollar mein. Har ek sambhaal kar rakhein.',
 /* 17 DGFT Portal */
 'DGFT Portal':'DGFT Portal',
 'Keep the promise':'Vaada nibhayein',
 'Match the receipt to the shipping bill.':'Raseed ko shipping bill se milayein.',
 'The bank receipt plus the shipping bill make the e-BRC, the government’s proof that the goods left and the money came home. It closes the LUT promise and unlocks export cash-back.':'Bank ki raseed aur shipping bill milkar e-BRC banate hain, sarkar ka saboot ki maal gaya aur paisa ghar aaya. Isse LUT ka vaada poora hota hai aur export cash-back khulta hai.',
 'Generate the closing certificate.':'Closing certificate banayein.',
 'Match and close':'Milayein aur band karein',
 'e-BRC issued. Promise kept. Shipment closed.':'e-BRC jaari. Vaada poora. Shipment band.',

 /* surprises */
 'Diwali week':'Diwali ka hafta',
 'The workers go home for Diwali. The factory stops for a week.':'Workers Diwali par ghar gaye. Factory ek hafte band.',
 'Wait, then restart':'Rukein, phir shuru karein',
 'Happy Diwali. Next time, plan production around the festival season.':'Happy Diwali. Agli baar tyohaar ka season dekhkar production plan karein.',
 'A call from “Amazon”':'“Amazon” se call',
 'A caller says he works for Amazon. He wants the OTP that just came to your phone.':'Caller kehta hai wo Amazon se hai. Use wo OTP chahiye jo abhi aapke phone par aaya.',
 'Hang up and report it':'Phone kaatein, report karein',
 'Right. Amazon never asks for an OTP or a password on a call.':'Sahi. Amazon call par kabhi OTP ya password nahi maangta.',
 'Read out the OTP':'OTP bata dein',
 'He takes over your seller account and changes the bank details. Never share an OTP with anyone.':'Usne aapka seller account le liya aur bank details badal di. OTP kabhi kisi ko na batayein.',
 'Monsoon at the port':'Port par monsoon',
 'Heavy rain at the port. The cranes stop, and your ship sails late.':'Port par tez baarish. Cranes ruk gayi, jahaz der se chalega.',
 'Wait it out':'Intezaar karein',
 'One week lost. From June to September, add spare time to sea shipments.':'Ek hafta gaya. June se September tak samundari shipment mein extra time rakhein.',
 'Random customs check':'Achanak customs check',
 'US customs picks your boxes for a check. An officer opens one and looks closely.':'US customs ne check ke liye aapke boxes chune. Officer ek box kholkar dhyan se dekhta hai.',
 'Show the papers':'Kaagaz dikhayein',
 'Made in India on every pack, and the FDA papers match. Cleared in two days.':'Har pack par Made in India, aur FDA ke kaagaz match. Do din mein clear.',
 'Made in India on every toy, and the test certificate is ready. Cleared in two days.':'Har khilone par Made in India, aur test certificate taiyaar. Do din mein clear.',
 'Made in India and the fibre label are sewn in. Cleared in two days.':'Made in India aur fibre label sile hue hain. Do din mein clear.',
 'Made in India is marked on every bottle. Cleared in two days.':'Har bottle par Made in India likha hai. Do din mein clear.',
 'Made in India, the Drug Facts label and the NDC number all match FDA’s list. Cleared in two days.':'Made in India, Drug Facts label aur NDC number, sab FDA ki list se match. Do din mein clear.',
 'A shopper has a question':'Ek shopper ka sawaal',
 'Honest and quick. The answer stays on the page and helps the next shopper decide.':'Sachcha aur jaldi. Jawab page par rehta hai aur agle shopper ki madad karta hai.',
 'Three units went missing':'Teen units gum ho gaye',
 'Amazon’s warehouse lost 3 of your units.':'Amazon ke warehouse ne aapke 3 units kho diye.',
 'File a claim':'Claim file karein',
 'Amazon pays you back for stock it loses. Check your stock report every month.':'Amazon khoye stock ke paise wapas deta hai. Har mahine apni stock report check karein.',
 'Let it go':'Jaane dein',
 'That was your money. Amazon pays back lost stock when you ask.':'Wo aapka paisa tha. Maangne par Amazon khoye stock ke paise deta hai.',
 'A copycat on your page':'Aapke page par nakalchi',
 'Another seller is selling a cheap fake on your listing and taking your sales.':'Koi aur seller aapki listing par sasta nakli maal bech raha hai aur aapki sales le raha hai.',
 'Report it in Brand Registry':'Brand Registry mein report karein',
 'Removed in two days. Without Brand Registry, it can take weeks of emails.':'Do din mein hat gaya. Brand Registry ke bina hafton tak emails chalti.',
 'Good news on the rupee':'Rupaye par achhi khabar',
 'The dollar now buys {now}, not {was}. Your payout is worth more.':'Ab ek dollar {now} ka hai, {was} ka nahi. Aapke payout ki keemat badh gayi.',
 'Nice!':'Badhiya!',
 'Same dollars, more rupees. Rates move both ways, so never plan on it.':'Wahi dollar, zyada rupaye. Rate dono taraf chalta hai, isliye iske bharose plan na karein.',
 'April: a new financial year':'April: naya financial year',
 'Months have passed. It is April, when two things need renewing.':'Mahine beet gaye. April aa gaya, do cheezein renew karni hain.',
 'Renew both':'Dono renew karein',
 'IEC confirmed on DGFT, fresh LUT filed on GST. Miss either and exporting gets harder.':'DGFT par IEC confirm, GST par naya LUT file. Ek bhi chhoota to export mushkil ho jaata hai.',
 'IEC confirmed on DGFT. You paid tax upfront, so there is no LUT to renew, and that refund is still in the queue.':'DGFT par IEC confirm. Aapne tax pehle bhara tha, isliye renew karne ko LUT nahi hai, aur wo refund abhi bhi line mein hai.',
 'Maker A’s bill':'Maker A ka bill',
 'Maker A does great work, and charges for it: 15% more on every unit.':'Maker A kaam badhiya karta hai, aur uske paise leta hai: har unit par 15% zyada.',
 'Pay the bill':'Bill bharein',
 'You were warned. Quality costs more, so budget for it.':'Aapko bataya gaya tha. Quality mehengi hoti hai, uska budget rakhein.',
 'The reviews are in':'Reviews aa gaye',
 'Some customers got faulty units.':'Kuch customers ko kharab units mile.',
 'Refund them':'Refund karein',
 '{n} bad units an inspector would have caught reached customers. You pay the refunds, and two 1-star reviews stay on your page.':'Jo {n} kharab units inspector pakad leta, wo customers tak pahunch gaye. Refund aapki jeb se, aur do 1-star reviews page par reh gaye.',

 /* year 2 */
 'Confirm your exporter ID':'Apna exporter ID confirm karein',
 'A yearly update, April to June.':'Saal ka update, April se June.',
 'Your IEC is yours for life, but DGFT switches it off if you skip the yearly update. Nothing changed? Confirm it anyway.':'IEC zindagi bhar aapka hai, par saal ka update chhoda to DGFT use band kar deta hai. Kuch nahi badla? Phir bhi confirm karein.',
 'Log in to DGFT and confirm your details.':'DGFT par login karke apni details confirm karein.',
 'Update my IEC':'Mera IEC update karein',
 'Confirmed for this year. Every shipping paper keeps working.':'Is saal ke liye confirm. Har shipping kaagaz chalta rahega.',
 'File this year’s promise letter':'Is saal ki vaade ki chitthi file karein',
 'An LUT lasts one financial year.':'LUT ek financial year chalta hai.',
 'Every April, file a fresh Letter of Undertaking. Skip it and the next exports need 18% tax paid upfront.':'Har April naya Letter of Undertaking file karein. Chhoda to agle export par 18% tax pehle bharna padega.',
 'File the LUT for the new financial year.':'Naye financial year ka LUT file karein.',
 'File a fresh LUT':'Naya LUT file karein',
 'Filed online for the new year. No tax paid upfront.':'Naye saal ke liye online file ho gaya. Pehle koi tax nahi.',
 'Your first LUT. This year no tax money gets stuck in a refund queue.':'Aapka pehla LUT. Is saal tax ka paisa refund ki line mein nahi atkega.',
 'How big is this year’s batch?':'Is saal ka batch kitna bada?',
 'Bigger batches tie up more cash.':'Bade batch mein zyada paisa atakta hai.',
 'The trademark, tests, photos and listing are done and paid for. Now it is about cash: bigger batches cost less per unit to ship, but every rupee sits in boxes until Amazon pays you.':'Trademark, tests, photos aur listing ho chuke, paise bhi bhar diye. Ab baat cash ki hai: bade batch mein har unit bhejna sasta padta hai, par Amazon ke paise dene tak har rupaya boxes mein band rehta hai.',
 'You have {cash} in the bank. How many units this year?':'Bank mein {cash} hain. Is saal kitne units?',
 '{n} units':'{n} units',
 'The safe size. Same stock, same sales as last year.':'Safe size. Pichhle saal jitna stock, utni sales.',
 'Double the stock. Shipping each unit gets cheaper.':'Double stock. Har unit bhejna sasta.',
 'A big bet. Cheapest per unit, and the most cash tied up.':'Bada daanv. Har unit sabse sasta, aur sabse zyada paisa atka.',
 'Money is tight: this needs about {need} and you have {cash}. The bank lends you the gap until Amazon pays.':'Paisa kam hai: iske liye lagbhag {need} chahiye aur aapke paas {cash} hain. Amazon ke paise aane tak baaki bank udhaar deta hai.',
 'That needs about {need} for making, shipping, duty and ads. You have {cash}. Pick a size you can pay for.':'Iske liye banane, bhejne, duty aur ads mein lagbhag {need} chahiye. Aapke paas {cash} hain. Utna chunein jitna bhar sakein.',
 'Bad units found and fixed before shipping. A bigger batch takes the inspector longer.':'Kharab units bhejne se pehle pakde aur theek kiye. Bade batch mein inspector ko zyada samay lagta hai.',
 'The new batch sets sail':'Naya batch ravana',
 'Same route, bigger load.':'Wahi raasta, zyada maal.',
 'Your freight forwarder and US customs setup carry over from last year. Only the load and the speed are new choices.':'Freight forwarder aur US customs ka setup pichhle saal wala hi hai. Sirf maal aur speed naye faisle hain.',
 'How do {n} units cross?':'{n} units kaise jaayenge?',
 'Cheap, and cheaper per unit the more you send. About 7 weeks.':'Sasta, aur jitna zyada bhejein har unit utna sasta. Lagbhag 7 hafte.',
 'Fast, but air is paid by weight. The bill grows with every unit.':'Tez, par hawai jahaz mein vajan ke hisaab se paise lagte hain. Har unit ke saath bill badhta hai.',
 'US customs, same as last year.':'US customs, pichhle saal jaisa.',
 'Broker files the entry':'Broker entry file karta hai',
 'Your broker imports in your name again.':'Broker phir se aapke naam se import karta hai.',
 'Renew the yearly bond':'Saal ka bond renew karein',
 'Bond renewed. You stay the importer.':'Bond renew ho gaya. Importer aap hi hain.',
 'A new shipping bill for this batch. It stays open until the money comes home.':'Is batch ka naya shipping bill. Paisa ghar aane tak khula rahega.',
 'Back in America':'Wapas America mein',
 'Pay duty, roll on.':'Duty bharein, aage badhein.',
 'Restock and sell':'Stock bharein aur bechein',
 'Your reviews carry over.':'Aapke reviews saath rehte hain.',
 'Last year’s reviews stay on the listing, so this batch starts with trust. Ads still bring the first visits.':'Pichhle saal ke reviews listing par rehte hain, isliye ye batch bharose ke saath shuru hota hai. Pehle visitors ab bhi ads se aate hain.',
 'Stock live again, next to last year’s reviews.':'Stock phir se live, pichhle saal ke reviews ke saath.',
 'Ads this year?':'Is saal ads?',
 'Enough clicks to keep the listing near the top.':'Itne clicks ki listing upar bani rahe.',
 'More than the listing needs. Reviews do part of the work now.':'Listing ki zaroorat se zyada. Ab reviews bhi kuch kaam karte hain.',
 'Delivered again':'Phir se deliver',
 'A repeat customer ordered two.':'Purane customer ne do mangaye.',

 /* on screen */
 'spent':'kharch',
 'left':'baaki',
 'week':'hafta',
 'weeks':'hafte',
 'YEAR {n}':'SAAL {n}',
 'Passport':'Passport',
 'Hold the right side to walk, or tap Walk':'Chalne ke liye daayin taraf dabaye rakhein, ya Chalein tap karein',
 'done last year':'pichhle saal ho gaya',
 'done':'ho gaya',
 'you are here':'aap yahan hain',
 'next stop':'agla stop',
 'later':'baad mein',
 'stamp earned':'stamp mila',
 'SURPRISE!':'ACHANAK!',
 'Stop {n}: {place}':'Stop {n}: {place}',
 'Your {stamp} stamp protects you here.':'Aapka {stamp} stamp yahan aapko bachata hai.',
 'Hide the explanation':'Explanation chhupayein',
 'Show the explanation':'Explanation dikhayein',
 'Tap the one your box will carry. You can change your mind before Next.':'Jo cheez box mein jaayegi us par tap karein. Aage badhne se pehle man badal sakte hain.',
 'Next':'Aage',
 'Name your brand. It goes on every box.':'Apne brand ka naam rakhein. Ye har box par jaayega.',
 'BRAND NAME':'BRAND KA NAAM',
 'Rename':'Naam badlein',
 'Name it':'Naam rakhein',
 'Change':'Badlein',
 'Done here':'Yahan ho gaya',
 'Next stop: {place}':'Agla stop: {place}',
 'Year {n} · Next stop: {place}':'Saal {n} · Agla stop: {place}',
 'The boxes board the ship. Long crossing ahead.':'Boxes jahaz par chadh gaye. Lamba safar aage.',
 'Walk on. Hold the right side of the picture, or tap the button.':'Aage chalein. Tasveer ki daayin taraf dabaye rakhein, ya button tap karein.',
 'Walk':'Chalein',
 'Set sail':'Jahaz chalayein',
 'Hurry!':'Jaldi!',
 'Hurrying…':'Jaldi-jaldi…',
 'Your brand':'Aapka brand',
 'Your box':'Aapka box',
 'Journey complete':'Safar poora',
 'Year complete':'Saal poora',
 '{brand} went from a workshop in India to a home in America and the money came back.':'{brand} India ke workshop se America ke ghar tak gaya, aur paisa wapas aaya.',
 '{brand} finished year {n}, and the money came home again.':'{brand} ka saal {n} poora, aur paisa phir ghar aaya.',
 'Your results stay here. Share your score, run the business for another year, or start over with another product.':'Aapke results yahin rahenge. Score share karein, business ek saal aur chalayein, ya naye product se phir shuru karein.',
 'Start year {n}':'Saal {n} shuru karein',
 'See results':'Results dekhein',
 'Share':'Share karein',
 'Play again, new product':'Phir khelein, naya product',
 'YOU MADE IT TO THE END':'AAP AAKHIR TAK PAHUNCH GAYE',
 'That means you will enjoy our live online session. Ask real exporters everything this game could not answer.':'Matlab aapko hamara live online session pasand aayega. Asli exporters se wo sab poochhiye jo ye game nahi bata paaya.',
 'Keep going with Edock’s live sessions, where people who export for real answer your questions.':'Edock ke live sessions ke saath aage badhein, jahan asli exporters aapke sawaalon ke jawab dete hain.',
 'Save my seat · from {price}':'Meri seat pakki karein · {price} se',
 'See upcoming sessions':'Aane wale sessions dekhein',
 'Opens edock.io in a new tab.':'edock.io naye tab mein khulega.',
 'Close':'Band karein',
 'From an Indian workshop to an American doorstep':'Indian workshop se American darwaze tak',
 'Carry one box through 17 stops. Tap, pick, stamp. Every price is in dollars and rupees. Music plays, so turn the sound up or tap the speaker to mute.':'Ek box ko 17 stops se le jaayein. Tap karein, chunein, stamp lein. Har daam dollar aur rupaye mein. Music bajta hai, awaaz badhayein ya speaker tap karke band karein.',
 'Continue':'Jaari rakhein',
 'See my results':'Mere results dekhein',
 'Continue year {n}':'Saal {n} jaari rakhein',
 'New game':'Naya game',
 'Tap to start':'Shuru karne ke liye tap karein',
 'A plain-words game about exporting from India and selling on Amazon USA. Example numbers at ₹84 per dollar, not advice. Free and open source under the MIT license.':'India se export karke Amazon USA par bechne ka, seedhi bhasha mein game. Numbers sirf misaal hain, ₹84 per dollar par, salah nahi. MIT license ke saath free aur open source.',
 'Passport · {n} / {total} stamps':'Passport · {n} / {total} stamps',
 'Tap a stamp to see what it means.':'Stamp par tap karke uska matlab dekhein.',
 'Not yet.':'Abhi nahi mila.',
 'Every official word in this journey, collected as a stamp.':'Is safar ka har sarkari shabd, stamp ke roop mein.',
 'Back to the road':'Wapas raaste par',
 'Restart journey':'Safar dobara shuru karein',
 'Yes, start over':'Haan, shuru se',
 'Keep going':'Chalte rahein',
 'Music is off. Tap to turn on.':'Music band hai. Chalu karne ke liye tap karein.',
 'Music is on. Tap to mute.':'Music chalu hai. Band karne ke liye tap karein.',

 /* results */
 '{brand} made it home':'{brand} ghar pahunch gaya',
 '{brand}: year {n} done':'{brand}: saal {n} poora',
 '{n} units of {product} sold in the USA at {price} each. Here is where the dollars went.':'USA mein {n} units bike ({product}), har ek {price} mein. Dekhiye dollar kahan gaye.',
 'Score {n} / 100':'Score {n} / 100',
 'Best {n}':'Best {n}',
 'wrong picks':'galat chunaav',
 'costly picks':'mehenge chunaav',
 '100 points, minus 6 for each wrong pick, 3 for each costly pick, and 1 for each week over {par}.':'100 points se shuru. Har galat chunaav par 6 kam, har mehenge chunaav par 3, aur {par} se upar har hafte par 1.',
 'Share on WhatsApp':'WhatsApp par bhejein',
 'Save picture':'Photo save karein',
 'Amazon fee':'Amazon fee',
 'Warehouse + delivery':'Warehouse + delivery',
 'Currency change':'Currency badalna',
 'Yours':'Aapka',
 'Customers paid':'Customers ne diye',
 'Amazon’s 15% cut':'Amazon ka 15% hissa',
 'Warehouse and delivery fee':'Warehouse aur delivery fee',
 'Dollars to rupees, 3%':'Dollar se rupaye, 3%',
 'Landed in your bank':'Aapke bank mein aaya',
 'You started with':'Shuruaat mein the',
 'You started the year with':'Saal ki shuruaat mein the',
 'You spent':'Aapne kharch kiye',
 'First batch result':'Pehle batch ka nateeja',
 'Next batch, same {n} units':'Agla batch, wahi {n} units',
 'This year’s result':'Is saal ka nateeja',
 'Last year’s result':'Pichhle saal ka nateeja',
 'Weeks on the road':'Raaste mein hafte',
 'Stamps collected':'Stamps mile',
 'The first batch already paid for the setup. Everything from here is easier.':'Pehle batch ne hi setup ka kharcha nikaal diya. Ab aage sab aasaan hai.',
 'The first batch paid for the setup: trademark, tests, photos, bond. Those never repeat. The next batch is where the profit lives.':'Pehle batch ne setup ka kharcha uthaya: trademark, tests, photos, bond. Ye dobara nahi lagte. Asli munafa agle batch mein hai.',
 'Better than last year. The setup is paid for, so more of every sale is yours.':'Pichhle saal se behtar. Setup ka kharcha ho chuka, isliye har sale ka zyada hissa aapka.',
 'Less than last year. A bigger batch ties up more cash, and costly picks add up.':'Pichhle saal se kam. Bade batch mein zyada paisa atakta hai, aur mehenge chunaav jud jaate hain.',
 'Your 18% tax deposit came back after 7 months: {amount}.':'Aapka 18% tax 7 mahine baad wapas aaya: {amount}.',
 'Example numbers at ₹84 per dollar. Rules and duty rates change; check before you spend.':'Numbers sirf misaal hain, ₹84 per dollar par. Rules aur duty rate badalte rehte hain, kharch se pehle check karein.',
 'Read the full written guide':'Poori likhit guide padhein',

 /* the share picture and message */
 'Can you beat me? Play free:':'Mujhse aage nikal sakte ho? Free mein khelo:',
 '{weeks} weeks · {wrong} wrong picks · {stamps} stamps':'{weeks} hafte · {wrong} galat chunaav · {stamps} stamps',
 'I took my {brand} {product} from India to America in {weeks} weeks and ranked {rank} ({score}/100) in The Journey of One Box. Can you beat me? {url}':'Maine apna {brand} ({product}) {weeks} hafte mein India se America pahunchaya. The Journey of One Box mein mera rank: {rank} ({score}/100). Mujhse aage nikal sakte ho? {url}',
 'Year {n} of my export business: {units} {brand} {product}s sold in America. I ranked {rank} ({score}/100) in The Journey of One Box. Can you beat me? {url}':'Mere export business ka saal {n}: America mein {brand} ({product}) ke {units} units bike. The Journey of One Box mein mera rank: {rank} ({score}/100). Mujhse aage nikal sakte ho? {url}'
};
const LANG_KEY='one-box-lang';
let LANG=(()=>{try{return localStorage.getItem(LANG_KEY)==='hinglish'?'hinglish':'en';}catch(e){return 'en';}})();
/* Lines with letters in them that have no Hinglish yet, collected as they show up.
   To check a playthrough, type [...HINGLISH_MISSING] in the browser console. */
const HINGLISH_MISSING=new Set();
function t(s){if(LANG!=='hinglish'||typeof s!=='string')return s;const h=HINGLISH[s];if(h!=null)return h;if(/[a-z]/i.test(s))HINGLISH_MISSING.add(s);return s;}
/* A line with {names} in it. Filled-in words are translated too when they are known lines, such as
   a product or stamp name; numbers and brand names pass through untouched. */
function tf(s,v){const w=x=>{x=String(x);return LANG==='hinglish'&&HINGLISH[x]!=null?HINGLISH[x]:x;};return t(s).replace(/\{(\w+)\}/g,(m,k)=>v&&v[k]!=null?w(v[k]):m);}
/* Content can hold a plain line or a [line, {names}] pair. */
function tx(x){return Array.isArray(x)?tf(x[0],x[1]):t(x);}
